Bump twisted from 22.1.0 to 22.2.0 (#88)
* Bump twisted from 22.1.0 to 22.2.0

Bumps [twisted](https://github.com/twisted/twisted) from 22.1.0 to 22.2.0.
- [Release notes](https://github.com/twisted/twisted/releases)
- [Changelog](https://github.com/twisted/twisted/blob/twisted-22.2.0/NEWS.rst)
- [Commits](https://github.com/twisted/twisted/compare/twisted-22.1.0...twisted-22.2.0)

---
updated-dependencies:
- dependency-name: twisted
  dependency-type: direct:production
...

Signed-off-by: dependabot[bot] <support@github.com>

* Upgrade 3 libraries to make it install andcompile in v3.9 and v3.10

* Lower numpy version. python v3.7 support was dropped by numpy

* Few upgrades of the test tools:

Upgrade mypy to avoid 'error: syntax error in type comment'
Upgrade pytest alnd pluggy to avoid 'AttributeError: str object has no attribute name'
Follow https://github.com/marketplace/actions/coveralls-github-action to
send coverage

* Let pip install a newer version of PyJWT to avoid: ImportError: cannot import name 'Iterable' from 'collections'

Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
Co-authored-by: Alvaro Gonzalez <alvaro.gonzalez@csc.fi>